In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(arr)
print(repr(arr))

[1. 2. 3. 4. 5.]
array([1., 2., 3., 4., 5.], dtype=float32)


# NUMPY

In [4]:
two_d = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]], dtype=np.float32)
print(two_d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
arr[0] = 10
print(arr)

[10  2  3  4  5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, np.nan])
print(np.isnan(arr))
print(arr)

[False False False False False  True]
[ 1.  2.  3.  4.  5. nan]


In [10]:
arr = np.arange(5)
print(arr)

arr = np.arange(5, 10)
print(repr(arr))

arr = np.arange(5, 50, 2)
print(repr(arr))

arr = np.arange(5.2, 10)
print(repr(arr))

[0 1 2 3 4]
array([5, 6, 7, 8, 9])
array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])
array([5.2, 6.2, 7.2, 8.2, 9.2])


In [15]:
arr = np.linspace(5, 11, num=3)
print(repr(arr))

arr = np.linspace(0, 11, num=4, endpoint=False, dtype=np.int32)
print(arr)

array([ 5.,  8., 11.])
[0 2 5 8]


In [18]:
arr = np.arange(8)
print(repr(arr))
reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))

flattened = reshaped_arr.flatten()
print(repr(flattened))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
array([0, 1, 2, 3, 4, 5, 6, 7])


In [19]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
